apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trustank-api
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10 # the pod should be up for at least 10sec before we can consider it stable
  selector:
    matchLabels:
      app: trustank-api
  template:
    metadata:
      labels:
        app: trustank-api
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          ports:
            - containerPort: 8080 # replace with the port your app listens on
          env:
            - name: MONGO_URI
              value: mongodb://my-mongodb-service:27017/my-db # replace with your own MongoDB URI