apiVersion: v1
kind: Service
metadata:
  name: trustank-api-service
spec:
  selector:
    app: trustank-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # replace with the port your app listens on
  type: LoadBalancer # change as needed depending on your use case
